version: '3.8'

services:
  api:
    build: ./student_api
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - student_net

  frontend1:
    build: ./student_frontend
    container_name: frontend1
    networks:
      - student_net

  frontend2:
    build: ./student_frontend
    container_name: frontend2
    networks:
      - student_net

  frontend3:
    build: ./student_frontend
    container_name: frontend3
    networks:
      - student_net

  nginx:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - student_net

networks:
  student_net:
    driver: bridge
